name: yandex_homework_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  analysis_chart:
    path: packages/analysis_chart

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  http: ^1.4.0
  intl: ^0.20.2
  hive:            ^2.2.3
  hive_flutter:    ^1.1.0
  sensors_plus: ^6.1.1
  fuzzy: ^0.5.1
  fl_chart: ^1.0.0
  dio: ^5.8.0+1
  uuid: ^4.5.1
  connectivity_plus: ^6.1.4
  worker_manager: ^7.2.6
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_icons:
  android: true          
  ios: true              
  image_path: "assets/app_icon.png"


flutter_native_splash:
  color: "#FFFFFF"             
  image: assets/app_icon.png     
  android: true
  ios: true
  android_gravity: center


dependency_overrides:
  source_gen: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/noise.png
    - assets/.env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
